name: Bug report
description: Report a bug with the TTT Bots
title: "[Bug]: <Enter bug title here>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "\* = mandatory"

  - type: dropdown
    id: game_version_server_type
    attributes:
      label: "Game version/server type *"
      description: "Select the server type and TTT version"
      options:
        - label: "Server Type"
          options:
            - "P2P"
            - "SRCDS"
            - "ALL"
        - label: "Which TTT"
          options:
            - "TTT"
            - "TTT2"
            - "BOTH"
        - label: "Version of Bots"
          options:
            - "Run the ttt_bot_version command to see the current version."

  - type: textarea
    id: describe_the_bug
    attributes:
      label: "Describe the bug *"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the issue you encountered..."

  - type: textarea
    id: stack_trace_error
    attributes:
      label: "Stack trace/error"
      description: "The error, if any."
      placeholder: |
        Example:
        
        [ttt bots 2] addons/ttt bots 2 electric boogaloo/lua/tttbots2/lib/botlib.lua:893: attempt to index a nil value
          1. GetConVarBool - addons/ttt bots 2 electric boogaloo/lua/tttbots2/lib/botlib.lua:893
           2. fn - addons/ttt bots 2 electric boogaloo/lua/autorun/server/tttbots-main.lua:112
            3. Run - lua/ulib/shared/hook.lua:109
             4. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:1211

        Timer Failed! [prep2begin][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 1013)]
      render: shell
    validations:
      required: false

  - type: textarea
    id: reproducing_the_bug
    attributes:
      label: "Reproducing the bug *"
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior *"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "E.g., 'There should not be any errors thrown,' or 'The bots shouldn't die after sending a chat message.'"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Screenshots are always appreciated but not required (depending on the bug)."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Providing extra context, including a mod collection or simple mod list, can hugely boost the speed at which your report gets addressed/resolved."
    validations:
      required: false
