name: Bug report
description: Report a bug with the TTT Bots
title: "[Bug]: <Enter bug title here>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit an issue! Please fill the below forms to the best of your ability.

        If your bug is related to support for another add-on (which is not already supported by TTT Bots), please create a feature request instead.

  - type: dropdown
    id: server_type
    attributes:
      label: "Server hosting type"
      description: "How is the server being hosted? If you are unsure, pick P2P."
      options:
        - "P2P"
        - "SRCDS"
        - "ALL"
    validations:
      required: true

  - type: dropdown
    id: ttt_type
    attributes:
      label: "TTT Type"
      description: "Please select the version of TTT you are using. If you are unsure, just select TTT."
      options:
        - "TTT"
        - "TTT2"
        - "BOTH"
    validations:
      required: true

  - type: input
    id: bot_version
    attributes:
      label: "Version of Bots"
      description: "Run the ttt_bot_version command to see the current version."
      placeholder: "E.g., v1.0.0"
    validations:
      required: true

  - type: textarea
    id: describe_the_bug
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the issue you encountered..."
    validations:
      required: true

  - type: textarea
    id: stack_trace_error
    attributes:
      label: "Stack trace/error"
      description: "The error, if any."
      placeholder: |
        Example:
        
        [ttt bots 2] addons/ttt bots 2 electric boogaloo/lua/tttbots2/lib/botlib.lua:893: attempt to index a nil value
          1. GetConVarBool - addons/ttt bots 2 electric boogaloo/lua/tttbots2/lib/botlib.lua:893
           2. fn - addons/ttt bots 2 electric boogaloo/lua/autorun/server/tttbots-main.lua:112
            3. Run - lua/ulib/shared/hook.lua:109
             4. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:1211

        Timer Failed! [prep2begin][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 1013)]
      render: shell
    validations:
      required: false

  - type: textarea
    id: reproducing_the_bug
    attributes:
      label: "Reproducing the bug"
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "E.g., 'There should not be any errors thrown,' or 'The bots shouldn't die after sending a chat message.'"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Screenshots are always appreciated but not required (depending on the bug)."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Providing extra context, including a mod collection or simple mod list, can hugely boost the speed at which your report gets addressed/resolved."
    validations:
      required: false

  - type: input
    id: credit-preferences
    attributes:
      label: GitHub Username Credit (NOT REQUIRED)
      description: |
        Please enter ONE appropriate username below (preferably yours) to be added to the TTT Bot contributors name list.

        Note: This process is NOT automatic, so it may take some time before your name is added. I reserve the right to reject any names, and offer zero warranty.

        Leave blank if you'd rather not have bots named after you.
      placeholder: "E.g., 'example_user'"
